const FormExample = [
    {
        "data":[
           {
              "type":0,
              "resetInUnmount":true,
              "propName":"AbleToAct",
              "helperText":"",
              "uid":"ableToAct",
              "title":"ניתן לבצע מדידה ",
              "subTitle":"",
              "placeHolder":"",
              "childComponents":{
                 "children":[
                    {
                       "type":1000,
                       "resetInUnmount":true,
                       "propName":"yesAble",
                       "helperText":"",
                       "uid":"yesAble",
                       "title":"כן",
                       "subTitle":"",
                       "placeHolder":"",
                       "label":"כן",
                       "componentId":"1"
                    },
                    {
                       "type":1000,
                       "resetInUnmount":true,
                       "propName":"notAble",
                       "helperText":"",
                       "uid":"notAble",
                       "title":"לא",
                       "subTitle":"",
                       "placeHolder":"",
                       "label":"לא",
                       "componentId":"2"
                    }
                 ],
                 "components":[
                    {
                       "id":"1",
                       "component":{
                          "type":4,
                          "resetInUnmount":true,
                          "propName":"SketchUploader",
                          "helperText":"סקיצה",
                          "uid":"sketchUploader",
                          "title":"סקיצה",
                          "subTitle":"",
                          "placeHolder":"",
                          "finalStep":true
                       }
                    },
                    {
                       "id":"2",
                       "component":{
                          "type":1,
                          "resetInUnmount":true,
                          "propName":"unAbleToMeasure",
                          "helperText":"",
                          "uid":"unAbleToMeasure",
                          "title":"סיבה",
                          "subTitle":"",
                          "placeHolder":"",
                          "finalStep":false,
                          "childComponents":{
                             "children":[
                                {
                                   "type":1000,
                                   "resetInUnmount":true,
                                   "propName":"jonuerInProp",
                                   "helperText":"",
                                   "uid":"jonuerInProp",
                                   "title":"",
                                   "subTitle":"",
                                   "placeHolder":"",
                                   "label":"הרוס",
                                   "componentId":"1",
                                   "finalStep":true
                                },
                                {
                                   "type":1000,
                                   "resetInUnmount":true,
                                   "propName":"noOneInProp",
                                   "helperText":"",
                                   "uid":"noOneInProp",
                                   "title":"",
                                   "subTitle":"",
                                   "placeHolder":"",
                                   "label":"בבנייה",
                                   "componentId":"1",
                                   "finalStep":true
                                },
                                {
                                   "type":1000,
                                   "resetInUnmount":true,
                                   "propName":"runner",
                                   "helperText":"",
                                   "uid":"runner",
                                   "title":"",
                                   "subTitle":"",
                                   "placeHolder":"",
                                   "label":"לא אותר",
                                   "componentId":"1",
                                   "finalStep":true
                                },
                              
                                {
                                   "type":1000,
                                   "resetInUnmount":true,
                                   "propName":"unableToMeasure",
                                   "helperText":"",
                                   "uid":"unableToMeasure",
                                   "title":"",
                                   "subTitle":"",
                                   "placeHolder":"",
                                   "label":"לא ניתן לבצע הערכה",
                                   "componentId":"2"
                                }
                             ],
                             "components":[
                                {
                                   "id":"1",
                                   "component":{
                                      "type":1000,
                                      "resetInUnmount":false,
                                      "propName":"",
                                      "helperText":"",
                                      "uid":"ui9",
                                      "title":"",
                                      "subTitle":"",
                                      "placeHolder":"",
                                      "finalStep":true
                                   }
                                },
                                {
                                   "id":"2",
                                   "component":{
                                      "type":3,
                                      "resetInUnmount":true,
                                      "propName":"comments",
                                      "helperText":"",
                                      "uid":"comments",
                                      "title":"הערות",
                                      "subTitle":"",
                                      "placeHolder":"נא לצין הערות",
                                      "multiLine":true,
                                      "finalStep":true
                                   }
                                }
                             ]
                          }
                       }
                    }
                 ]
              }
           },
           {
              "type":2,
              "resetInUnmount":true,
              "propName":"unableToTakePic",
              "helperText":"",
              "uid":"unableToTakePic",
              "title":"",
              "subTitle":"",
              "placeHolder":"",
              "finalStep":true,
              "childComponents":{
                 "children":[
                    {
                       "type":1000,
                       "resetInUnmount":true,
                       "propName":"unableToTackImage",
                       "helperText":"",
                       "uid":"unableToTackImage",
                       "title":"",
                       "subTitle":"",
                       "placeHolder":"",
                       "label":"לא ניתן לצלם",
                       "componentId":"1",
                       "finalStep":true
                    }
                 ],
                 "components":[
                    {
                       "id":"1",
                       "component":{
                          "type":3,
                          "resetInUnmount":true,
                          "propName":"imageComments",
                          "helperText":"",
                          "uid":"imageComments",
                          "title":"הערות",
                          "subTitle":"",
                          "placeHolder":"נא לצין הערות",
                          "multiLine":true,
                          "finalStep":true
                       }
                    }
                 ]
              }
           }
        ],
        "createBy":"2020-03-15",
        "createDate":1615120571042,
        "project":2,
        "formName":null,
        "type":4
     }
]
export default FormExample